### ISSUE TITLE
ETA on new release?

### ISSUE THREAD

**Issue by NeckBeardPrince** [inket/stts#107]
or even a way for us to build a new release?

**Comment by inket** [comment]
You can build the app yourself using Xcode.

You will need to fetch/build the dependencies first using Carthage:
```sh
$ brew install carthage
$ carthage update --platform osx
```

For the next release, I'm waiting until I have enough time to finish https://github.com/inket/stts/issues/103 since it's about halfway done.

**Comment by inket** [comment]
1.19 was just released on the App Store so I'm closing this.
