### ISSUE TITLE
cannot install dependencies

### ISSUE THREAD

**Issue by enokoneko** [inket/stts#151]
```
➜  stts git:(master) bundle install
Traceback (most recent call last):
	2: from /usr/bin/bundle:23:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.2.16) required by your /Users/danis/stts/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.2.16`
```
and of couse I tried the following two commands, neither of which worked.

**Comment by inket** [comment]
Would this solution work? https://stackoverflow.com/a/66843669/528645

If not, just delete `Gemfile.lock` or delete the bundler version requirement from there.
You should be able to run `gem install bundler && bundle install` without issues.

---

If that doesn't work, it's not worth the trouble to fiddle with it. Ruby gems and installations are exhausting and I completely forgot that 🤦‍♂️ 

If you just need to build the app, you can do it without the gems (you just need to install the Carthage dependencies).
If you want to add services, feel free to give me the links I'll add them myself.

**Comment by enokoneko** [comment]
Thank you for your reply.

I'm not very computer literate and following the code on the forum doesn't seem to work.

I just wish to add this service: https://status.workflowy.com
🙏

**Comment by inket** [comment]
Totally! It should be in the next version (could be a week or two from now)
