### ISSUE TITLE
Google Cloud seems to be broken

### ISSUE THREAD

**Issue by selfagency** [inket/stts#173]
Hello again wonderful maintainer of wonderful software! I'm just writing to let you know that it appears Google may have changed the config for their status page, as this has been like this for a couple of weeks now:

![CleanShot 2022-04-04 at 19 04 59](https://user-images.githubusercontent.com/2541728/161646591-1a5f6c65-4560-4ef5-88c5-b686a00f6e15.png)

If and when you have the chance, your attention to this issue would be appreciated.

Thank you!

**Comment by inket** [comment]
Thanks for reporting this! Like you said, it seems they changed their status pages completely. I'm looking into it.

 Please don't hesitate to report anything not working~

**Comment by bondskin** [comment]
same with me

**Comment by bondskin** [comment]
@inket Apple (All) is shown as "the request timed out"

**Comment by inket** [comment]
Update was submitted to Apple and should be available today/tomorrow!

**Comment by bondskin** [comment]
thanks @inket , new update is now working as expected. That was super fast.

**Comment by inket** [comment]
Great! I'll close this issue now. If you find any other issues feel free to create an issue!

(note to myself: fixed with https://github.com/inket/stts/commit/311a65714a11aa80925cbc5a606d064ec8ff2ace)
