### ISSUE TITLE
Apple (All) "the request timed out"

### ISSUE THREAD

**Issue by bondskin** [inket/stts#174]
Hi,

I have enabled the Apple (All) option and I get after a while "the request timed out".
Is this because there are too many services which need to be checked?

After waiting a while, it is shown with green check mark

**Comment by inket** [comment]
I think it might be a connection problem on your side or Apple's side. I will keep an eye on it in case other people start having the same issue though.

> Is this because there are too many services which need to be checked?

Apple (All) only loads [this page](https://www.apple.com/support/systemstatus/) and checks that the green dots are there.
