### ISSUE TITLE
Atlassian wrong status

### ISSUE THREAD

**Issue by chmez** [inket/stts#183]
As you can see [here](https://status.atlassian.com/) Atlassian has some issues with Jira Software right now:

![atlassian](https://user-images.githubusercontent.com/11755359/170469534-695d34bf-20a8-4eda-86c5-8c65cbd7c2d3.png)

but the "stts" application says that everything is fine:

![stts](https://user-images.githubusercontent.com/11755359/170469553-edef5d98-1654-420c-bfc5-b68d6d33f72c.png)

**Comment by inket** [comment]
Oh. It seems Atlassian used to have one status page for all its services at status.atlassian.com, but now that changed and they have a status page for each of their services, however API-wise they kept status.atlassian.com...

Will be fixed in the next version.

**Comment by bondskin** [comment]
@inket amazing support 🙏🏻
