### ISSUE TITLE
Incorrect status for Cloudflare

### ISSUE THREAD

**Issue by crstauf** [inket/stts#197]
cloudflarestatus.com is currently reporting an incident ([archive](https://web.archive.org/web/20221117174211/https://www.cloudflarestatus.com/)), but the app is showing "All systems operational".

**Comment by crstauf** [comment]
Refreshing the list does not fix the issue.

**Comment by inket** [comment]
Thanks for reporting this!

**Comment by inket** [comment]
Of course when I have time to work on this the web archive is down 🤦‍♂️ Hopefully it'll be up tonight otherwise it'll have to wait for the next version.

**Comment by crstauf** [comment]
:tada:
