### ISSUE TITLE
Pivotal Tracker & Papertrail

### ISSUE THREAD

**Issue by serogers** [inket/stts#20]
Hi there. I'm loving this app, thanks for making it! 

Could you add support for [Pivotal Tracker](https://status.pivotaltracker.com) and [Papertrail](https://www.papertrailstatus.com)? I believe they both use StatusPage.

**Comment by inket** [comment]
Hi! Glad you like the app.

I added Pivotal Tracker and Papertrail and they should be available in the next update of the app.

Will close this issue once that update hits the App Store.

🤗

**Comment by serogers** [comment]
Excellent. Thanks a bunch!
