### ISSUE TITLE
status.typeform.com

### ISSUE THREAD

**Issue by joshRpowell** [inket/stts#21]
Hi, 

Great app!  I found the most recent additions to be helpful. 

Typeform uses statuspage.io

I would submit a PR, but didn't know where to find the statusPageId.

**Comment by inket** [comment]
Hi! Glad that you like app :)

I went ahead and added Typeform myself. Should be in the next version of the app once it's approved.

An easy way to find the ID is to open [/api](http://status.typeform.com/api) and click any of the links. The api's subdomain is the ID, so in this case `http://fv5fyw3p7k8n.statuspage.io/api/v2/summary.json`, `fv5fyw3p7k8n` is what we're looking for.
