### ISSUE TITLE
[Service request] Pipedrive and Postmark

### ISSUE THREAD

**Issue by pkat** [inket/stts#223]
Would love to see the following services added:

- Pipedrive - https://status.pipedrive.com/ 
  - API - https://status.postmarkapp.com/api/v1/status
  - Page Id: 2754
- Postmark - https://status.postmarkapp.com/ 
  - API - https://status.pipedrive.com/api/v1/status
  - Page Id: 12903

They both appear to be using the [Sorry app](https://www.sorryapp.com/).

**Comment by inket** [comment]
Thank you for providing the page IDs!
