### ISSUE TITLE
https://status.digitalocean.com/

### ISSUE THREAD

**Issue by fabbrikk** [inket/stts#37]
Digitalocean status page is changed an isn't working anymore.

**Comment by inket** [comment]
Yup! Will look into it. It's so annoying.

**Comment by inket** [comment]
Can you update the app through the App Store and check again? Are you on v1.1.5?

**Comment by fabbrikk** [comment]
Ok. Updated to 1.1.5 on MBP and it's ok. When I return on imac i'll do the same. Thanks!

**Comment by fabbrikk** [comment]
Perfect! Latest version 1.1.5 works. Strange that App store was not asking me to upgrade from version 1.1.0 but it's ok,my fault.
