### ISSUE TITLE
Zwift not an option: Version 1.1.10 (18)

### ISSUE THREAD

**Issue by joshRpowell** [inket/stts#48]
![monosnap 2018-02-27 12-24-26](https://user-images.githubusercontent.com/6732638/36743840-414f5100-1bb9-11e8-8010-f1706adb9379.png)

**Comment by inket** [comment]
Indeed... I forgot to add the file to the Xcode project after merging it. I will release a new version tonight.

**Comment by joshRpowell** [comment]
👍 ride on!

[Joshua Powell - Contact Using Hop](http://GetHop.com/?_hmid=1519818239)

On February 28, 2018 at 2:28 GMT, Mahdi Bchatnia <notifications@github.com> wrote:

Indeed... I forgot to add the file to the Xcode project after merging it. I will release a new version tonight.

**Comment by inket** [comment]
New version was released on the App Store today. Zwift should show be the list now. Thanks for reporting it!
