### ISSUE TITLE
bartender compatibility issue

### ISSUE THREAD

**Issue by selfagency** [inket/stts#49]
i use [bartender](https://www.macbartender.com/), a popular mac os extension, to hide menu bar items that i don't use as frequently. unfortunately, for some reason, when you click the bartender menu icon and not the stts icon, the stts dropdown opens.

![screenflick movie](https://user-images.githubusercontent.com/2541728/37744539-141fd0bc-2d46-11e8-8ecd-74e8f4540aff.gif)

**Comment by inket** [comment]
Funny issue, lol. I will check it tonight.

**Comment by inket** [comment]
Should be fixed in the next version. (It's Waiting for Review by Apple now)

Should be out tomorrow. Thank you for reporting this bug!

**Comment by selfagency** [comment]
awesome, thanks!
