### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by joshRpowell** [inket/stts#54]
Is this the first using [Cachet](https://cachethq.io/)? - http://status.yarnpkg.com/

**Comment by inket** [comment]
Yes, it is the first time. Luckily they have an API so this should be easy. I'll add it 👍

**Comment by inket** [comment]
I added it in https://github.com/inket/stts/commit/e9970a70ff5ac1d18fed88431fd7738b3b69813a & https://github.com/inket/stts/commit/773fdfca43a32142f8e34bcea8c9bac50caf698f - should be in the next update 👍
