### ISSUE TITLE
Support for PayPal statuses

### ISSUE THREAD

**Issue by danemacmillan** [inket/stts#59]
Hi! I just found this utility, and like its simplicity.

PayPal operates many services, and they provide detailed status/uptime information for all of them. Given that PayPal is a major service for processing payments, it would be nice to know when it goes down. 

https://www.paypal-status.com/product/production

There is *a lot* of information on these pages, so I'll suggest the following as good first candidates:
- product/production/Online Checkout
- api/production/SOAP & NVP APIs/Express Checkout APIs

I'm targeting these as good first candidates because those two areas account for almost all Magento and Magento2 framework calls to PayPal. Magento has a huge market share in ecommerce, so these are useful to anyone who relies on these services.

**Comment by inket** [comment]
Cool! Should be in the next version.

**Comment by danemacmillan** [comment]
Amazing! I also noticed you pushed an update for #60. Thanks a bunch. I wasn't expecting such responsiveness.
