### ISSUE TITLE
Google Cloud Platform support

### ISSUE THREAD

**Issue by Tapppi** [inket/stts#6]
Hi, I'm interested in getting GCP support. Mainly Google container engine, compute engine, but the more the merrier. I'd be happy to help out, even though my Swift skills are rusty. Is there a simple description of the process to add services? If not, I'd be happy to help in writing it out after learning to do it :smile: 

Absolutely lovely tool by the way 👍

**Comment by inket** [comment]
Hi @Tapppi! Thanks for the kind words.

Right now it might be faster to let me do it, until I work on documenting the process for adding services.

Would you happen to know if there's a better API for https://status.cloud.google.com ? Right now there is a JSON Feed which is just a list of incidents, but I'm looking for something like a summary of the current status.

I might have to just parse the page's HTML source, but then I would be making assumptions about how it would look like when the status is not "ok", seeing as it hasn't been down for quite a few weeks.

**Comment by Tapppi** [comment]
I couldn't find anything else, but when you parse that list, you can create the current status, no? Basically, if none of the lists incidents are active at the moment, everything is ok. Everything out of the ordinary is active in the list. I think that would be why they created a feed instead of a static status api.

**Comment by inket** [comment]
Hi again!

Support for Google Cloud Platform was added here: https://github.com/inket/stts/commit/1732dea7e41d93a459982468d75bdfd526da643e and the new version of the app is waiting for review for release to the App Store.

Tell me how it works out for you once you try it!

**Comment by inket** [comment]
Closing this as the version with GCP support was released in the App Store a few days ago. Please open a new issue if you encounter any problems!

**Comment by Tapppi** [comment]
Working great, thank you!
