### ISSUE TITLE
Permanent loading for Google Cloud

### ISSUE THREAD

**Issue by arslanbekov** [inket/stts#83]
macOS Mojave `10.14.5`
stts `1.10 (34)`

I check all google cloud services and have permanent loading.
<img width="226" alt="Screenshot 2019-05-21 at 17 41 34" src="https://user-images.githubusercontent.com/579213/58105880-e2900400-7bef-11e9-9f5a-75d14e9fb877.png">

**Comment by inket** [comment]
Hi! Does restarting the app fix it?

**Comment by arslanbekov** [comment]
@inket ha, thanks ;) it's fixed it

**Comment by inket** [comment]
If you find how to reproduce it well, please tell me!

**Comment by arslanbekov** [comment]
@inket hi, it seems I know how can reproduce. Reboot mac (before reboot needed check in preferences `Start at Login` - enable). And after the restart, all google cloud services in status - `Loading...`

I checked this two times.

**Comment by inket** [comment]
Thanks!
